name: Build NodeJS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.17.1
        
    - name: Run npm bild
      working-directory: nodejs
      run: |
        npm i
        npm i lodash
        npm run build

    - name: Commit NodeJS Config files
      working-directory: nodejs/dist
      run: |
        git add -f index.config.js
        git add -f index.config.js.md5
        git add -f index.js
        git add -f index.js.md5
        commit_msg="* 发布 CatVodOpen新源"
        git commit -a -m "$commit_msg"

    - name: Push NodelJS Config Changes To Gitee
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GE_TOKEN }}
        repository: ${{ secrets.GE_PATH }}
        directory: .
        branch: dist
        force: true
        github_url: https://gitee.com
        
    - name: Archive dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: |
          nodejs/dist
